name: ArmorStandRemover
version: 1.0
api-version: 1.15
description: Removes armor stand that is no longer used by the chair plugin.
author: kubotan
main: space.gorogoro.armorstandremover.ArmorStandRemover
